export const statusStyles = {
  Available: {
    labelKey: "availableNow",
    badge: "bg-emerald-50 text-emerald-700 ring-emerald-200",
    marker: "bg-emerald-500",
    order: 0
  },
  "Almost Full": {
    labelKey: "almostFull",
    badge: "bg-amber-50 text-amber-700 ring-amber-200",
    marker: "bg-amber-500",
    order: 1
  },
  Full: {
    labelKey: "full",
    badge: "bg-rose-50 text-rose-700 ring-rose-200",
    marker: "bg-rose-500",
    order: 2
  }
};

const japanesePlaceNames = [
  ["광화문", "光化門"],
  ["종각", "鐘閣"],
  ["명동", "明洞"],
  ["서울역", "ソウル駅"],
  ["홍대", "弘大"],
  ["동대문역사문화공원", "東大門歴史文化公園"],
  ["동대문", "東大門"],
  ["인천공항", "仁川空港"],
  ["부산역", "釜山駅"],
  ["해운대", "海雲台"],
  ["제주공항", "済州空港"],
  ["서울대입구", "ソウル大入口"],
  ["강남구청", "江南区庁"],
  ["잠실나루", "蚕室ナル"],
  ["잠실새내", "蚕室セネ"],
  ["석촌고분", "石村古墳"],
  ["송파나루", "松坡ナル"],
  ["석계", "石渓"],
  ["암사", "岩寺"],
  ["몽촌토성", "夢村土城"],
  ["석촌", "石村"],
  ["송파", "松坡"],
  ["황리단길", "皇理団通り"],
  ["황리단길 생활문화센터", "皇理団通り生活文化センター"],
  ["동대구역", "東大邱駅"],
  ["강릉역", "江陵駅"],
  ["을지로3가", "乙支路3街"],
  ["을지로입구", "乙支路入口"],
  ["서울식물원", "ソウル植物園"],
  ["종합운동장", "総合運動場"],
  ["강남", "江南"],
  ["잠실", "蚕室"],
  ["시청", "市庁"],
  ["여의도", "汝矣島"],
  ["고속터미널", "高速ターミナル"],
  ["김포공항", "金浦空港"],
  ["김해공항", "金海空港"],
  ["제주시", "済州市"],
  ["수원시", "水原市"],
  ["수원", "水原"],
  ["광명시", "光明市"],
  ["성남시", "城南市"],
  ["고양시", "高陽市"],
  ["구리시", "九里市"],
  ["여수시", "麗水市"],
  ["전주시", "全州市"],
  ["양양군", "襄陽郡"],
  ["대구", "大邱"],
  ["부산", "釜山"],
  ["서울", "ソウル"],
  ["인천", "仁川"],
  ["제주", "済州"],
  ["경주", "慶州"],
  ["강릉", "江陵"],
  ["청량리", "清凉里"],
  ["제기동", "祭基洞"],
  ["신설동", "新設洞"],
  ["동묘앞", "東廟前"],
  ["동대문역사문화공원", "東大門歴史文化公園"],
  ["종로5가", "鍾路5街"],
  ["종로3가", "鍾路3街"],
  ["종합운동장", "総合運動場"],
  ["종각", "鐘閣"],
  ["시청", "市庁"],
  ["을지로4가", "乙支路4街"],
  ["신당", "新堂"],
  ["상왕십리", "上往十里"],
  ["왕십리", "往十里"],
  ["한양대", "漢陽大"],
  ["뚝섬", "トゥクソム"],
  ["용답", "龍踏"],
  ["신답", "新踏"],
  ["용두", "龍頭"],
  ["성수", "聖水"],
  ["건대입구", "建大入口"],
  ["구의", "九宜"],
  ["합정", "合井"],
  ["삼성", "三成"],
  ["선릉", "宣陵"],
  ["잠실", "蚕室"],
  ["모란", "牡丹"],
  ["단대오거리", "丹垈オゴリ"],
  ["남한산성입구", "南漢山城入口"],
  ["산성", "山城"],
  ["수진", "寿進"],
  ["신흥", "新興"],
  ["철산", "鉄山"],
  ["광명사거리", "光明サゴリ"],
  ["지축", "紙杻"],
  ["장자호수공원", "長者湖水公園"],
  ["갈매중앙공원", "葛梅中央公園"],
  ["행궁사랑채", "行宮サランチェ"],
  ["화홍사랑채", "華虹サランチェ"],
  ["이순신 광장", "李舜臣広場"],
  ["죽도해변 사물함", "竹島海辺 ロッカー"],
  ["낙산 문화관광해설사의 집 사물함", "洛山文化観光解説の家 ロッカー"]
];

const localizedLockerNames = {
  ko: {
    "Gwanghwamun Public Locker Center": "광화문 공영 물품보관함",
    "Myeongdong Station Smart Locker": "명동역 스마트 물품보관함",
    "Seoul Station Travel Locker": "서울역 여행자 물품보관함",
    "Hongdae Tourist Locker": "홍대 관광 물품보관함",
    "Dongdaemun Design Plaza Locker": "동대문디자인플라자 물품보관함",
    "Incheon Airport Public Storage Desk": "인천공항 공영 짐보관소",
    "Busan Station Tourist Locker": "부산역 관광 물품보관함",
    "Haeundae Beach Public Locker": "해운대해수욕장 공영 물품보관함",
    "Jeju Airport Arrival Locker": "제주공항 도착층 물품보관함",
    "Gyeongju Historic Area Locker": "경주 역사관광지 물품보관함",
    "Dongdaegu Station Public Locker": "동대구역 공영 물품보관함",
    "Gangneung Station Easy Locker": "강릉역 간편 물품보관함",
    "Suwon Convention Center Locker": "수원컨벤션센터 물품보관함"
  },
  zh: {
    "Gwanghwamun Public Locker Center": "光化门公共储物柜",
    "Myeongdong Station Smart Locker": "明洞站智能储物柜",
    "Seoul Station Travel Locker": "首尔站旅客储物柜",
    "Hongdae Tourist Locker": "弘大游客储物柜",
    "Dongdaemun Design Plaza Locker": "东大门设计广场储物柜",
    "Incheon Airport Public Storage Desk": "仁川机场公共行李寄存处",
    "Busan Station Tourist Locker": "釜山站游客储物柜",
    "Haeundae Beach Public Locker": "海云台海水浴场公共储物柜",
    "Jeju Airport Arrival Locker": "济州机场到达层储物柜",
    "Gyeongju Historic Area Locker": "庆州历史景区储物柜",
    "Dongdaegu Station Public Locker": "东大邱站公共储物柜",
    "Gangneung Station Easy Locker": "江陵站储物柜",
    "Suwon Convention Center Locker": "水原会展中心储物柜"
  },
  ja: {
    "Gwanghwamun Public Locker Center": "光化門 公共ロッカー",
    "Myeongdong Station Smart Locker": "明洞駅 スマートロッカー",
    "Seoul Station Travel Locker": "ソウル駅 旅行者ロッカー",
    "Hongdae Tourist Locker": "弘大 観光ロッカー",
    "Dongdaemun Design Plaza Locker": "東大門デザインプラザ ロッカー",
    "Incheon Airport Public Storage Desk": "仁川空港 公共荷物預かり所",
    "Busan Station Tourist Locker": "釜山駅 観光ロッカー",
    "Haeundae Beach Public Locker": "海雲台海水浴場 公共ロッカー",
    "Jeju Airport Arrival Locker": "済州空港 到着階ロッカー",
    "Gyeongju Historic Area Locker": "慶州 歴史観光地ロッカー",
    "Dongdaegu Station Public Locker": "東大邱駅 公共ロッカー",
    "Gangneung Station Easy Locker": "江陵駅 かんたんロッカー",
    "Suwon Convention Center Locker": "水原コンベンションセンター ロッカー"
  }
};

const localizedDistricts = {
  en: {
    "Jongno-gu": "Jongno-gu",
    "Jung-gu": "Jung-gu",
    "Yongsan-gu": "Yongsan-gu",
    "Mapo-gu": "Mapo-gu",
    "Jung-gu, Incheon": "Jung-gu, Incheon",
    "Dong-gu, Busan": "Dong-gu, Busan",
    "Haeundae-gu, Busan": "Haeundae-gu, Busan",
    "Jeju-si": "Jeju-si",
    "Gyeongju-si": "Gyeongju-si",
    "Dong-gu, Daegu": "Dong-gu, Daegu",
    "Gangneung-si": "Gangneung-si",
    "Yeongtong-gu, Suwon": "Yeongtong-gu, Suwon",
    "Gangnam-gu": "Gangnam-gu",
    "Gangseo-gu": "Gangseo-gu",
    "Gwangjin-gu": "Gwangjin-gu",
    "Seocho-gu": "Seocho-gu",
    "Dongjak-gu": "Dongjak-gu",
    "Nowon-gu": "Nowon-gu",
    "Guro-gu": "Guro-gu",
    "Eunpyeong-gu": "Eunpyeong-gu",
    "Jungnang-gu": "Jungnang-gu",
    "Yangcheon-gu": "Yangcheon-gu",
    "Gwanak-gu": "Gwanak-gu",
    "Gangbuk-gu": "Gangbuk-gu",
    "Gangdong-gu": "Gangdong-gu",
    "Yeongdeungpo-gu": "Yeongdeungpo-gu",
    "Seongdong-gu": "Seongdong-gu",
    "Dongdaemun-gu": "Dongdaemun-gu",
    "Songpa-gu": "Songpa-gu",
    "Seodaemun-gu": "Seodaemun-gu",
    "Seongbuk-gu": "Seongbuk-gu",
    "Dobong-gu": "Dobong-gu",
    "Geumcheon-gu": "Geumcheon-gu",
    "Tongyeong-si": "Tongyeong-si",
    "Wando-gun": "Wando-gun",
    "Wansan-gu": "Wansan-gu",
    "Paldal-gu": "Paldal-gu",
    "Sujeong-gu": "Sujeong-gu",
    "강남구": "Gangnam-gu",
    "종로구": "Jongno-gu",
    "중구": "Jung-gu",
    "용산구": "Yongsan-gu",
    "마포구": "Mapo-gu",
    "인천 중구": "Jung-gu, Incheon",
    "부산 동구": "Dong-gu, Busan",
    "부산 해운대구": "Haeundae-gu, Busan",
    "제주시": "Jeju-si",
    "경주시": "Gyeongju-si",
    "대구 동구": "Dong-gu, Daegu",
    "강릉시": "Gangneung-si",
    "강서구": "Gangseo-gu",
    "광진구": "Gwangjin-gu",
    "서초구": "Seocho-gu",
    "동작구": "Dongjak-gu",
    "노원구": "Nowon-gu",
    "구로구": "Guro-gu",
    "은평구": "Eunpyeong-gu",
    "중랑구": "Jungnang-gu",
    "양천구": "Yangcheon-gu",
    "관악구": "Gwanak-gu",
    "강북구": "Gangbuk-gu",
    "강동구": "Gangdong-gu",
    "영등포구": "Yeongdeungpo-gu",
    "성동구": "Seongdong-gu",
    "동대문구": "Dongdaemun-gu",
    "송파구": "Songpa-gu",
    "서대문구": "Seodaemun-gu",
    "성북구": "Seongbuk-gu",
    "도봉구": "Dobong-gu",
    "금천구": "Geumcheon-gu",
    "수원시": "Suwon-si",
    "광명시": "Gwangmyeong-si",
    "성남시": "Seongnam-si",
    "고양시": "Goyang-si",
    "구리시": "Guri-si",
    "여수시": "Yeosu-si",
    "전주시": "Jeonju-si",
    "양양군": "Yangyang-gun",
    "통영시": "Tongyeong-si",
    "완도군": "Wando-gun",
    "완산구": "Wansan-gu",
    "팔달구": "Paldal-gu",
    "수정구": "Sujeong-gu",
    "덕양구": "Deogyang-gu"
  },
  ko: {
    "Jongno-gu": "종로구",
    "Jung-gu": "중구",
    "Yongsan-gu": "용산구",
    "Mapo-gu": "마포구",
    "Jung-gu, Incheon": "인천 중구",
    "Dong-gu, Busan": "부산 동구",
    "Haeundae-gu, Busan": "부산 해운대구",
    "Jeju-si": "제주시",
    "Gyeongju-si": "경주시",
    "Dong-gu, Daegu": "대구 동구",
    "Gangneung-si": "강릉시",
    "Yeongtong-gu, Suwon": "수원시 영통구",
    "Gangnam-gu": "강남구",
    "Gangseo-gu": "강서구",
    "Gwangjin-gu": "광진구",
    "Seocho-gu": "서초구",
    "Dongjak-gu": "동작구",
    "Nowon-gu": "노원구",
    "Guro-gu": "구로구",
    "Eunpyeong-gu": "은평구",
    "Jungnang-gu": "중랑구",
    "Yangcheon-gu": "양천구",
    "Gwanak-gu": "관악구",
    "Gangbuk-gu": "강북구",
    "Gangdong-gu": "강동구",
    "Yeongdeungpo-gu": "영등포구",
    "Seongdong-gu": "성동구",
    "Dongdaemun-gu": "동대문구",
    "Songpa-gu": "송파구",
    "Seodaemun-gu": "서대문구",
    "Seongbuk-gu": "성북구",
    "Dobong-gu": "도봉구",
    "Geumcheon-gu": "금천구",
    "Tongyeong-si": "통영시",
    "Wando-gun": "완도군",
    "Wansan-gu": "완산구",
    "Paldal-gu": "팔달구",
    "Sujeong-gu": "수정구",
    "강남구": "강남구",
    "강서구": "강서구",
    "광진구": "광진구",
    "서초구": "서초구",
    "동작구": "동작구",
    "노원구": "노원구",
    "구로구": "구로구",
    "은평구": "은평구",
    "중랑구": "중랑구",
    "양천구": "양천구",
    "관악구": "관악구",
    "강북구": "강북구",
    "강동구": "강동구",
    "영등포구": "영등포구",
    "성동구": "성동구",
    "동대문구": "동대문구",
    "송파구": "송파구",
    "서대문구": "서대문구",
    "성북구": "성북구",
    "도봉구": "도봉구",
    "금천구": "금천구",
    "여수시": "여수시",
    "전주시": "전주시",
    "양양군": "양양군",
    "통영시": "통영시",
    "완도군": "완도군",
    "완산구": "완산구",
    "팔달구": "팔달구",
    "수정구": "수정구"
  },
  zh: {
    "Jongno-gu": "钟路区",
    "Jung-gu": "中区",
    "Yongsan-gu": "龙山区",
    "Mapo-gu": "麻浦区",
    "Jung-gu, Incheon": "仁川中区",
    "Dong-gu, Busan": "釜山东区",
    "Haeundae-gu, Busan": "釜山海云台区",
    "Jeju-si": "济州市",
    "Gyeongju-si": "庆州市",
    "Dong-gu, Daegu": "大邱东区",
    "Gangneung-si": "江陵市",
    "Yeongtong-gu, Suwon": "水原市灵通区",
    "Gangnam-gu": "江南区",
    "Gangseo-gu": "江西区",
    "Gwangjin-gu": "广津区",
    "Seocho-gu": "瑞草区",
    "Dongjak-gu": "铜雀区",
    "Nowon-gu": "芦原区",
    "Guro-gu": "九老区",
    "Eunpyeong-gu": "恩平区",
    "Jungnang-gu": "中浪区",
    "Yangcheon-gu": "阳川区",
    "Gwanak-gu": "冠岳区",
    "Gangbuk-gu": "江北区",
    "Gangdong-gu": "江东区",
    "Yeongdeungpo-gu": "永登浦区",
    "Seongdong-gu": "城东区",
    "Dongdaemun-gu": "东大门区",
    "Songpa-gu": "松坡区",
    "Seodaemun-gu": "西大门区",
    "Seongbuk-gu": "城北区",
    "Dobong-gu": "道峰区",
    "Geumcheon-gu": "衿川区",
    "Tongyeong-si": "统营市",
    "Wando-gun": "莞岛郡",
    "Wansan-gu": "完山区",
    "Paldal-gu": "八达区",
    "Sujeong-gu": "寿井区",
    "강남구": "江南区",
    "강서구": "江西区",
    "광진구": "广津区",
    "서초구": "瑞草区",
    "동작구": "铜雀区",
    "노원구": "芦原区",
    "구로구": "九老区",
    "은평구": "恩平区",
    "중랑구": "中浪区",
    "양천구": "阳川区",
    "관악구": "冠岳区",
    "강북구": "江北区",
    "강동구": "江东区",
    "영등포구": "永登浦区",
    "성동구": "城东区",
    "동대문구": "东大门区",
    "송파구": "松坡区",
    "서대문구": "西大门区",
    "성북구": "城北区",
    "도봉구": "道峰区",
    "금천구": "衿川区",
    "여수시": "丽水市",
    "전주시": "全州市",
    "양양군": "襄阳郡",
    "통영시": "统营市",
    "완도군": "莞岛郡",
    "완산구": "完山区",
    "팔달구": "八达区",
    "수정구": "寿井区"
  },
  ja: {
    "Jongno-gu": "鍾路区",
    "Jung-gu": "中区",
    "Yongsan-gu": "龍山区",
    "Mapo-gu": "麻浦区",
    "Jung-gu, Incheon": "仁川 中区",
    "Dong-gu, Busan": "釜山 東区",
    "Haeundae-gu, Busan": "釜山 海雲台区",
    "Jeju-si": "済州市",
    "Gyeongju-si": "慶州市",
    "Dong-gu, Daegu": "大邱 東区",
    "Gangneung-si": "江陵市",
    "Yeongtong-gu, Suwon": "水原市 霊通区",
    "Gangnam-gu": "江南区",
    "Gangseo-gu": "江西区",
    "Gwangjin-gu": "広津区",
    "Seocho-gu": "瑞草区",
    "Dongjak-gu": "銅雀区",
    "Nowon-gu": "蘆原区",
    "Guro-gu": "九老区",
    "Eunpyeong-gu": "恩平区",
    "Jungnang-gu": "中浪区",
    "Yangcheon-gu": "陽川区",
    "Gwanak-gu": "冠岳区",
    "Gangbuk-gu": "江北区",
    "Gangdong-gu": "江東区",
    "Yeongdeungpo-gu": "永登浦区",
    "Seongdong-gu": "城東区",
    "Dongdaemun-gu": "東大門区",
    "Songpa-gu": "松坡区",
    "Seodaemun-gu": "西大門区",
    "Seongbuk-gu": "城北区",
    "Dobong-gu": "道峰区",
    "Geumcheon-gu": "衿川区",
    "Tongyeong-si": "統営市",
    "Wando-gun": "莞島郡",
    "Wansan-gu": "完山区",
    "Paldal-gu": "八達区",
    "Sujeong-gu": "寿井区",
    "강남구": "江南区",
    "강서구": "江西区",
    "광진구": "広津区",
    "서초구": "瑞草区",
    "동작구": "銅雀区",
    "노원구": "蘆原区",
    "구로구": "九老区",
    "은평구": "恩平区",
    "중랑구": "中浪区",
    "양천구": "陽川区",
    "관악구": "冠岳区",
    "강북구": "江北区",
    "강동구": "江東区",
    "영등포구": "永登浦区",
    "성동구": "城東区",
    "동대문구": "東大門区",
    "송파구": "松坡区",
    "서대문구": "西大門区",
    "성북구": "城北区",
    "도봉구": "道峰区",
    "금천구": "衿川区",
    "여수시": "麗水市",
    "전주시": "全州市",
    "양양군": "襄陽郡",
    "통영시": "統営市",
    "완도군": "莞島郡",
    "완산구": "完山区",
    "팔달구": "八達区",
    "수정구": "寿井区"
  }
};

const localizedAddresses = {
  ko: {
    "172 Sejong-daero, Jongno-gu, Seoul": "서울 종로구 세종대로 172",
    "Myeongdong Station Exit 6, Jung-gu, Seoul": "서울 중구 명동역 6번 출구",
    "Seoul Station Transfer Hall, 405 Hangang-daero": "서울역 환승통로, 한강대로 405",
    "Hongik University Station Exit 9, Mapo-gu, Seoul": "서울 마포구 홍대입구역 9번 출구",
    "DDP Visitor Center, Eulji-ro, Jung-gu": "서울 중구 을지로 DDP 관광안내센터",
    "Terminal 1 Arrival Hall, Incheon International Airport": "인천국제공항 제1터미널 도착층",
    "Busan Station Main Hall, Jungang-daero, Dong-gu, Busan": "부산 동구 중앙대로 부산역 맞이방",
    "Haeundae Beach Tourist Information Center, Busan": "부산 해운대해수욕장 관광안내소",
    "Jeju International Airport Arrival Hall, Jeju": "제주국제공항 도착층",
    "Hwangnidan-gil Tourist Information Area, Gyeongju": "경주 황리단길 관광안내 구역",
    "Dongdaegu Station Transfer Center, Dong-gu, Daegu": "대구 동구 동대구역 환승센터",
    "Gangneung Station Tourist Zone, Gangneung": "강릉역 관광안내 구역",
    "Suwon Convention Center, Gwanggyo Lake Park-ro, Suwon": "수원컨벤션센터, 광교호수공원로"
  },
  zh: {
    "172 Sejong-daero, Jongno-gu, Seoul": "首尔钟路区世宗大路172",
    "Myeongdong Station Exit 6, Jung-gu, Seoul": "首尔中区明洞站6号出口",
    "Seoul Station Transfer Hall, 405 Hangang-daero": "首尔站换乘通道，汉江大路405",
    "Hongik University Station Exit 9, Mapo-gu, Seoul": "首尔麻浦区弘大入口站9号出口",
    "DDP Visitor Center, Eulji-ro, Jung-gu": "首尔中区乙支路东大门设计广场游客中心",
    "Terminal 1 Arrival Hall, Incheon International Airport": "仁川国际机场第1航站楼到达层",
    "Busan Station Main Hall, Jungang-daero, Dong-gu, Busan": "釜山东区中央大路釜山站大厅",
    "Haeundae Beach Tourist Information Center, Busan": "釜山海云台海水浴场旅游咨询中心",
    "Jeju International Airport Arrival Hall, Jeju": "济州国际机场到达层",
    "Hwangnidan-gil Tourist Information Area, Gyeongju": "庆州皇理团路旅游咨询区",
    "Dongdaegu Station Transfer Center, Dong-gu, Daegu": "大邱东区东大邱站换乘中心",
    "Gangneung Station Tourist Zone, Gangneung": "江陵站旅游咨询区",
    "Suwon Convention Center, Gwanggyo Lake Park-ro, Suwon": "水原会展中心，光教湖水公园路"
  },
  ja: {
    "172 Sejong-daero, Jongno-gu, Seoul": "ソウル 鍾路区 世宗大路 172",
    "Myeongdong Station Exit 6, Jung-gu, Seoul": "ソウル 中区 明洞駅 6番出口",
    "Seoul Station Transfer Hall, 405 Hangang-daero": "ソウル駅 乗換通路、漢江大路 405",
    "Hongik University Station Exit 9, Mapo-gu, Seoul": "ソウル 麻浦区 弘大入口駅 9番出口",
    "DDP Visitor Center, Eulji-ro, Jung-gu": "ソウル 中区 乙支路 DDP観光案内センター",
    "Terminal 1 Arrival Hall, Incheon International Airport": "仁川国際空港 第1ターミナル 到着階",
    "Busan Station Main Hall, Jungang-daero, Dong-gu, Busan": "釜山 東区 中央大路 釜山駅コンコース",
    "Haeundae Beach Tourist Information Center, Busan": "釜山 海雲台海水浴場 観光案内所",
    "Jeju International Airport Arrival Hall, Jeju": "済州国際空港 到着階",
    "Hwangnidan-gil Tourist Information Area, Gyeongju": "慶州 皇理団通り 観光案内エリア",
    "Dongdaegu Station Transfer Center, Dong-gu, Daegu": "大邱 東区 東大邱駅 乗換センター",
    "Gangneung Station Tourist Zone, Gangneung": "江陵駅 観光案内エリア",
    "Suwon Convention Center, Gwanggyo Lake Park-ro, Suwon": "水原コンベンションセンター、光教湖水公園路"
  }
};

const localizedBusStops = {
  ko: {
    "Gwanghwamun Square": "광화문광장",
    "Myeongdong Entrance": "명동입구",
    "Seoul Station Bus Transfer Center": "서울역버스환승센터",
    "Hongik University Station": "홍대입구역",
    "Dongdaemun Design Plaza": "동대문디자인플라자",
    "Incheon Airport T1": "인천공항 T1",
    "Busan Station": "부산역",
    "Haeundae Beach": "해운대해수욕장",
    "Jeju International Airport": "제주국제공항",
    "Daereungwon Tomb Complex": "대릉원",
    "Dongdaegu Station Transfer Center": "동대구역 환승센터",
    "Gangneung Station": "강릉역",
    "Suwon Convention Center": "수원컨벤션센터"
  },
  zh: {
    "Gwanghwamun Square": "光化门广场",
    "Myeongdong Entrance": "明洞入口",
    "Seoul Station Bus Transfer Center": "首尔站公共交通换乘中心",
    "Hongik University Station": "弘大入口站",
    "Dongdaemun Design Plaza": "东大门设计广场",
    "Incheon Airport T1": "仁川机场 T1",
    "Busan Station": "釜山站",
    "Haeundae Beach": "海云台海水浴场",
    "Jeju International Airport": "济州国际机场",
    "Daereungwon Tomb Complex": "大陵苑",
    "Dongdaegu Station Transfer Center": "东大邱站换乘中心",
    "Gangneung Station": "江陵站",
    "Suwon Convention Center": "水原会展中心"
  },
  ja: {
    "Gwanghwamun Square": "光化門広場",
    "Myeongdong Entrance": "明洞入口",
    "Seoul Station Bus Transfer Center": "ソウル駅 バス乗換センター",
    "Hongik University Station": "弘大入口駅",
    "Dongdaemun Design Plaza": "東大門デザインプラザ",
    "Incheon Airport T1": "仁川空港 T1",
    "Busan Station": "釜山駅",
    "Haeundae Beach": "海雲台海水浴場",
    "Jeju International Airport": "済州国際空港",
    "Daereungwon Tomb Complex": "大陵苑",
    "Dongdaegu Station Transfer Center": "東大邱駅 乗換センター",
    "Gangneung Station": "江陵駅",
    "Suwon Convention Center": "水原コンベンションセンター"
  }
};

const localizedPrices = {
  ko: {
    "Small 2,000 KRW / Large 4,000 KRW": "소형 2,000원 / 대형 4,000원",
    "Small 2,000 KRW / Medium 3,000 KRW / Large 5,000 KRW":
      "소형 2,000원 / 중형 3,000원 / 대형 5,000원",
    "Small 2,000 KRW / Large 5,000 KRW": "소형 2,000원 / 대형 5,000원",
    "Small 2,000 KRW / Large 4,500 KRW": "소형 2,000원 / 대형 4,500원",
    "Small 2,000 KRW / Medium 3,000 KRW": "소형 2,000원 / 중형 3,000원",
    "Small 4,000 KRW / Large 8,000 KRW": "소형 4,000원 / 대형 8,000원",
    "Small 3,000 KRW / Large 6,000 KRW": "소형 3,000원 / 대형 6,000원",
    "요금 정보는 공공데이터 상세 API에서 확인하세요.": "요금 정보는 공공데이터 상세 API에서 확인하세요.",
    무료: "무료"
  },
  zh: {
    "Small 2,000 KRW / Large 4,000 KRW": "小型 2,000韩元 / 大型 4,000韩元",
    "Small 2,000 KRW / Medium 3,000 KRW / Large 5,000 KRW":
      "小型 2,000韩元 / 中型 3,000韩元 / 大型 5,000韩元",
    "Small 2,000 KRW / Large 5,000 KRW": "小型 2,000韩元 / 大型 5,000韩元",
    "Small 2,000 KRW / Large 4,500 KRW": "小型 2,000韩元 / 大型 4,500韩元",
    "Small 2,000 KRW / Medium 3,000 KRW": "小型 2,000韩元 / 中型 3,000韩元",
    "Small 4,000 KRW / Large 8,000 KRW": "小型 4,000韩元 / 大型 8,000韩元",
    "Small 3,000 KRW / Large 6,000 KRW": "小型 3,000韩元 / 大型 6,000韩元",
    "요금 정보는 공공데이터 상세 API에서 확인하세요.": "费用信息请以公共数据详情 API 为准。",
    무료: "免费"
  },
  ja: {
    "Small 2,000 KRW / Large 4,000 KRW": "小型 2,000ウォン / 大型 4,000ウォン",
    "Small 2,000 KRW / Medium 3,000 KRW / Large 5,000 KRW":
      "小型 2,000ウォン / 中型 3,000ウォン / 大型 5,000ウォン",
    "Small 2,000 KRW / Large 5,000 KRW": "小型 2,000ウォン / 大型 5,000ウォン",
    "Small 2,000 KRW / Large 4,500 KRW": "小型 2,000ウォン / 大型 4,500ウォン",
    "Small 2,000 KRW / Medium 3,000 KRW": "小型 2,000ウォン / 中型 3,000ウォン",
    "Small 4,000 KRW / Large 8,000 KRW": "小型 4,000ウォン / 大型 8,000ウォン",
    "Small 3,000 KRW / Large 6,000 KRW": "小型 3,000ウォン / 大型 6,000ウォン",
    "요금 정보는 공공데이터 상세 API에서 확인하세요.": "料金情報は公共データ詳細 API で確認してください。",
    무료: "無料"
  }
};

const localizedOpenHours = {
  ko: {
    "24 hours": "24시간 운영",
    "Open hours not provided": "운영시간 정보 없음"
  },
  zh: {
    "24 hours": "24小时营业",
    "Open hours not provided": "暂无营业时间信息"
  },
  ja: {
    "24 hours": "24時間営業",
    "Open hours not provided": "営業時間情報なし"
  }
};

const localizedBusRouteLabels = {
  ko: {
    "Public bus": "일반버스",
    Transfer: "환승"
  },
  zh: {
    "Public bus": "公共交通",
    Transfer: "换乘"
  },
  ja: {
    "Public bus": "一般バス",
    Transfer: "乗換"
  }
};

const englishTextReplacements = [
  ["서울특별시", "Seoul"],
  ["경기도", "Gyeonggi-do"],
  ["경상남도", "Gyeongsangnam-do"],
  ["경상북도", "Gyeongsangbuk-do"],
  ["전라남도", "Jeollanam-do"],
  ["전북특별자치도", "Jeonbuk State"],
  ["강원특별자치도", "Gangwon State"],
  ["인천국제공항", "Incheon International Airport"],
  ["제주국제공항", "Jeju International Airport"],
  ["서울역", "Seoul Station"],
  ["광화문", "Gwanghwamun"],
  ["명동", "Myeongdong"],
  ["홍대입구", "Hongik Univ."],
  ["서울식물원", "Seoul Botanic Park"],
  ["동대문역사문화공원", "Dongdaemun History & Culture Park"],
  ["동대문디자인플라자", "Dongdaemun Design Plaza"],
  ["홍대입구", "Hongik Univ."],
  ["서울대입구", "Seoul Nat'l Univ."],
  ["성신여대입구", "Sungshin Women's Univ."],
  ["한성대입구", "Hansung Univ."],
  ["동대입구", "Dongguk Univ."],
  ["총신대입구", "Chongshin Univ."],
  ["숭실대입구", "Soongsil Univ."],
  ["고속터미널", "Express Bus Terminal"],
  ["남부터미널", "Nambu Bus Terminal"],
  ["영등포구청", "Yeongdeungpo-gu Office"],
  ["양천구청", "Yangcheon-gu Office"],
  ["마포구청", "Mapo-gu Office"],
  ["강남구청", "Gangnam-gu Office"],
  ["강동구청", "Gangdong-gu Office"],
  ["경찰병원", "Police Hospital"],
  ["중앙보훈병원", "VHS Medical Center"],
  ["구로디지털단지", "Guro Digital Complex"],
  ["구로디지탈단지", "Guro Digital Complex"],
  ["디지털미디어시티", "Digital Media City"],
  ["월드컵경기장", "World Cup Stadium"],
  ["올림픽공원", "Olympic Park"],
  ["종합운동장", "Sports Complex"],
  ["잠실나루", "Jamsilnaru"],
  ["잠실새내", "Jamsilsaenae"],
  ["신정네거리", "Sinjeongnegeori"],
  ["석촌고분", "Seokchon Tombs"],
  ["송파나루", "Songpanaru"],
  ["한성백제", "Hanseong Baekje"],
  ["둔촌오륜", "Dunchon Oryun"],
  ["가산디지털", "Gasan Digital Complex"],
  ["단대오거리", "Dandaeogeori"],
  ["태릉입구", "Taereung"],
  ["문정", "Munjeong"],
  ["장지", "Jangji"],
  ["복정", "Bokjeong"],
  ["삼전", "Samjeon"],
  ["둔촌동", "Dunchon-dong"],
  ["굽은다리", "Gubeundari"],
  ["방이", "Bangi"],
  ["개롱", "Gaerong"],
  ["거여", "Geoyeo"],
  ["마천", "Macheon"],
  ["온수", "Onsu"],
  ["석계", "Seokgye"],
  ["청량리", "Cheongnyangni"],
  ["제기동", "Jegi-dong"],
  ["신설동", "Sinseol-dong"],
  ["동묘앞", "Dongmyo"],
  ["동대문", "Dongdaemun"],
  ["종로5가", "Jongno 5-ga"],
  ["종로3가", "Jongno 3-ga"],
  ["종각", "Jonggak"],
  ["시청", "City Hall"],
  ["을지로입구", "Euljiro 1-ga"],
  ["을지로3가", "Euljiro 3-ga"],
  ["을지로4가", "Euljiro 4-ga"],
  ["신당", "Sindang"],
  ["상왕십리", "Sangwangsimni"],
  ["왕십리", "Wangsimni"],
  ["한양대", "Hanyang Univ."],
  ["뚝섬", "Ttukseom"],
  ["용답", "Yongdap"],
  ["신답", "Sindap"],
  ["용두", "Yongdu"],
  ["성수", "Seongsu"],
  ["건대입구", "Konkuk Univ."],
  ["구의", "Guui"],
  ["강변", "Gangbyeon"],
  ["잠실", "Jamsil"],
  ["삼성", "Samseong"],
  ["선릉", "Seolleung"],
  ["역삼", "Yeoksam"],
  ["강남", "Gangnam"],
  ["신도림", "Sindorim"],
  ["독립문", "Dongnimmun"],
  ["교대", "Seoul Nat'l Univ. of Education"],
  ["서초", "Seocho"],
  ["방배", "Bangbae"],
  ["사당", "Sadang"],
  ["낙성대", "Nakseongdae"],
  ["봉천", "Bongcheon"],
  ["신림", "Sillim"],
  ["신대방", "Sindaebang"],
  ["대림", "Daerim"],
  ["도림천", "Dorimcheon"],
  ["문래", "Mullae"],
  ["당산", "Dangsan"],
  ["합정", "Hapjeong"],
  ["신촌", "Sinchon"],
  ["이대", "Ewha Womans Univ."],
  ["아현", "Ahyeon"],
  ["충정로", "Chungjeongno"],
  ["구파발", "Gupabal"],
  ["연신내", "Yeonsinnae"],
  ["불광", "Bulgwang"],
  ["녹번", "Nokbeon"],
  ["홍제", "Hongje"],
  ["무악재", "Muakjae"],
  ["경복궁", "Gyeongbokgung"],
  ["약수", "Yaksu"],
  ["금호", "Geumho"],
  ["옥수", "Oksu"],
  ["압구정", "Apgujeong"],
  ["신사", "Sinsa"],
  ["잠원", "Jamwon"],
  ["양재", "Yangjae"],
  ["매봉", "Maebong"],
  ["도곡", "Dogok"],
  ["대치", "Daechi"],
  ["학여울", "Hangnyeoul"],
  ["대청", "Daecheong"],
  ["일원", "Irwon"],
  ["수서", "Suseo"],
  ["가락시장", "Garak Market"],
  ["오금", "Ogeum"],
  ["불암산", "Bulamsan"],
  ["상계", "Sanggye"],
  ["노원", "Nowon"],
  ["창동", "Chang-dong"],
  ["쌍문", "Ssangmun"],
  ["수유", "Suyu"],
  ["미아사거리", "Miasageori"],
  ["미아", "Mia"],
  ["길음", "Gireum"],
  ["혜화", "Hyehwa"],
  ["충무로", "Chungmuro"],
  ["회현", "Hoehyeon"],
  ["숙대입구", "Sookmyung Women's Univ."],
  ["삼각지", "Samgakji"],
  ["신용산", "Sinyongsan"],
  ["이촌", "Ichon"],
  ["동작", "Dongjak"],
  ["남태령", "Namtaeryeong"],
  ["방화", "Banghwa"],
  ["개화산", "Gaehwasan"],
  ["김포공항", "Gimpo Airport"],
  ["송정", "Songjeong"],
  ["마곡", "Magok"],
  ["발산", "Balsan"],
  ["우장산", "Ujangsan"],
  ["화곡", "Hwagok"],
  ["까치산", "Kkachisan"],
  ["신정", "Sinjeong"],
  ["목동", "Mok-dong"],
  ["오목교", "Omokgyo"],
  ["양평", "Yangpyeong"],
  ["영등포시장", "Yeongdeungpo Market"],
  ["신길", "Singil"],
  ["여의도", "Yeouido"],
  ["여의나루", "Yeouinaru"],
  ["마포", "Mapo"],
  ["애오개", "Aeogae"],
  ["서대문", "Seodaemun"],
  ["청구", "Cheonggu"],
  ["신금호", "Singeumho"],
  ["행당", "Haengdang"],
  ["마장", "Majang"],
  ["답십리", "Dapsimni"],
  ["장한평", "Janghanpyeong"],
  ["군자", "Gunja"],
  ["아차산", "Achasan"],
  ["광나루", "Gwangnaru"],
  ["천호", "Cheonho"],
  ["강동", "Gangdong"],
  ["길동", "Gil-dong"],
  ["명일", "Myeongil"],
  ["고덕", "Godeok"],
  ["상일동", "Sangil-dong"],
  ["응암", "Eungam"],
  ["역촌", "Yeokchon"],
  ["독바위", "Dokbawi"],
  ["구산", "Gusan"],
  ["새절", "Saejeol"],
  ["증산", "Jeungsan"],
  ["망원", "Mangwon"],
  ["상수", "Sangsu"],
  ["광흥창", "Gwangheungchang"],
  ["대흥", "Daeheung"],
  ["공덕", "Gongdeok"],
  ["효창공원앞", "Hyochang Park"],
  ["녹사평", "Noksapyeong"],
  ["이태원", "Itaewon"],
  ["버티고개", "Beotigogae"],
  ["창신", "Changsin"],
  ["보문", "Bomun"],
  ["안암", "Anam"],
  ["고려대", "Korea Univ."],
  ["월곡", "Wolgok"],
  ["상월곡", "Sangwolgok"],
  ["돌곶이", "Dolgoji"],
  ["화랑대", "Hwarangdae"],
  ["봉화산", "Bonghwasan"],
  ["도봉산", "Dobongsan"],
  ["수락산", "Suraksan"],
  ["마들", "Madeul"],
  ["중계", "Junggye"],
  ["하계", "Hagye"],
  ["공릉", "Gongneung"],
  ["먹골", "Meokgol"],
  ["중화", "Junghwa"],
  ["상봉", "Sangbong"],
  ["면목", "Myeonmok"],
  ["사가정", "Sagajeong"],
  ["용마산", "Yongmasan"],
  ["중곡", "Junggok"],
  ["어린이대공원", "Children's Grand Park"],
  ["자양", "Jayang"],
  ["청담", "Cheongdam"],
  ["학동", "Hakdong"],
  ["논현", "Nonhyeon"],
  ["반포", "Banpo"],
  ["내방", "Naebang"],
  ["이수", "Isu"],
  ["남성", "Namseong"],
  ["상도", "Sangdo"],
  ["장승배기", "Jangseungbaegi"],
  ["신대방삼거리", "Sindaebang Samgeori"],
  ["보라매", "Boramae"],
  ["신풍", "Sinpung"],
  ["남구로", "Namguro"],
  ["천왕", "Cheonwang"],
  ["암사", "Amsa"],
  ["몽촌토성", "Mongchontoseong"],
  ["석촌", "Seokchon"],
  ["송파", "Songpa"],
  ["행궁사랑채", "Haenggung Sarangchae"],
  ["화홍사랑채", "Hwahong Sarangchae"],
  ["웅천친수공원", "Ungcheon Waterfront Park"],
  ["오동도 주차장", "Odongdo Parking Lot"],
  ["명사십리해수욕장", "Myeongsasimni Beach"],
  ["황리단길 생활문화센터", "Hwangnidan-gil Community Center"],
  ["경기전 여행자 라운지", "Gyeonggijeon Traveler Lounge"],
  ["전주종합관광안내소", "Jeonju Tourist Information Center"],
  ["중앙시장", "Jungang Market"],
  ["서호시장", "Seoho Market"],
  ["고객지원센터", "Customer Support Center"],
  ["관광안내소", "Tourist Information Center"],
  ["생활문화센터", "Community Center"],
  ["여행자 라운지", "Traveler Lounge"],
  ["사물함", "Locker"],
  ["물품보관함", "Locker"],
  ["공영", "Public"],
  ["여행자", "Traveler"],
  ["관광", "Tourist"],
  ["기본요금", "Base fare"],
  ["추가요금", "Extra fare"],
  ["최대5시간", "up to 5 hours"],
  ["4시간", "4 hours"],
  ["부과 이후", "after the base period"],
  ["1시간당", "per hour"],
  ["발생", "applies"],
  ["소형", "Small"],
  ["중형", "Medium"],
  ["대형", "Large"],
  ["무료", "Free"],
  ["지하", "Underground "],
  ["왕산로", "Wangsan-ro"],
  ["세종대로", "Sejong-daero"],
  ["한강대로", "Hangang-daero"],
  ["화랑로", "Hwarang-ro"],
  ["동일로", "Dongil-ro"],
  ["마곡동로", "Magokdong-ro"],
  ["종로", "Jong-ro"],
  ["지봉로", "Jibong-ro"],
  ["율곡로", "Yulgok-ro"],
  ["돈화문로11길", "Donhwamun-ro 11-gil"],
  ["돈화문로", "Donhwamun-ro"],
  ["서소문로", "Seosomun-ro"],
  ["경인로114가길", "Gyeongin-ro 114-gil"],
  ["경인로67길", "Gyeongin-ro 67-gil"],
  ["경인로3길", "Gyeongin-ro 3-gil"],
  ["을지로", "Eulji-ro"],
  ["창경궁로", "Changgyeonggung-ro"],
  ["장충단로", "Jangchungdan-ro"],
  ["마른내로", "Mareunnae-ro"],
  ["퇴계로", "Toegye-ro"],
  ["다산로", "Dasan-ro"],
  ["왕십리로", "Wangsimni-ro"],
  ["아차산로", "Achasan-ro"],
  ["용답길", "Yongdap-gil"],
  ["천호대로", "Cheonho-daero"],
  ["능동로", "Neungdong-ro"],
  ["강변역로", "Gangbyeonyeok-ro"],
  ["오금로", "Ogeum-ro"],
  ["올림픽로", "Olympic-ro"],
  ["테헤란로", "Teheran-ro"],
  ["강남대로", "Gangnam-daero"],
  ["일원로", "Irwon-ro"],
  ["서초대로", "Seocho-daero"],
  ["방배로", "Bangbae-ro"],
  ["남부순환로", "Nambusunhwan-ro"],
  ["동작대로", "Dongjak-daero"],
  ["대림로", "Daerim-ro"],
  ["도림천로", "Dorimcheon-ro"],
  ["도림로", "Dorim-ro"],
  ["목동로3길", "Mokdong-ro 3-gil"],
  ["중앙로", "Jungang-ro"],
  ["새말로", "Saemal-ro"],
  ["당산로", "Dangsan-ro"],
  ["양산로", "Yangsan-ro"],
  ["양화로", "Yanghwa-ro"],
  ["공항대로", "Airport-daero"],
  ["강서로", "Gangseo-ro"],
  ["양재대로", "Yangjae-daero"],
  ["증산로", "Jeungsan-ro"],
  ["신촌로", "Sinchon-ro"],
  ["진관2로", "Jingwan 2-ro"],
  ["통일로", "Tongil-ro"],
  ["사직로", "Sajik-ro"],
  ["동호로", "Dongho-ro"],
  ["압구정로", "Apgujeong-ro"],
  ["도산대로", "Dosan-daero"],
  ["잠원로4길", "Jamwon-ro 4-gil"],
  ["신반포로", "Sinbanpo-ro"],
  ["서초중앙로", "Seochojungang-ro"],
  ["광평로", "Gwangpyeong-ro"],
  ["중대로", "Jungdae-ro"],
  ["상계로", "Sanggye-ro"],
  ["마들로11길", "Madeul-ro 11-gil"],
  ["도봉로", "Dobong-ro"],
  ["동소문로", "Dongsomun-ro"],
  ["삼선교로", "Samseongyo-ro"],
  ["대학로", "Daehak-ro"],
  ["서빙고로", "Seobinggo-ro"],
  ["현충로", "Hyeonchung-ro"],
  ["과천대로", "Gwacheon-daero"],
  ["금낭화로", "Geumnanghwa-ro"],
  ["양천로", "Yangcheon-ro"],
  ["하늘길", "Haneul-gil"],
  ["화곡로", "Hwagok-ro"],
  ["오목로", "Omok-ro"],
  ["여의나루로", "Yeouinaru-ro"],
  ["여의동로", "Yeouidong-ro"],
  ["이태원로", "Itaewon-ro"],
  ["마포대로", "Mapo-daero"],
  ["청구로", "Cheonggu-ro"],
  ["금호로", "Geumho-ro"],
  ["행당로", "Haengdang-ro"],
  ["마장로", "Majang-ro"],
  ["고덕로", "Godeok-ro"],
  ["서오릉로", "Seoroereung-ro"],
  ["불광로", "Bulgwang-ro"],
  ["연서로", "Yeonseo-ro"],
  ["수색로", "Susaek-ro"],
  ["월드컵로", "World Cup-ro"],
  ["독막로", "Dokmak-ro"],
  ["대흥로", "Daeheung-ro"],
  ["백범로", "Baekbeom-ro"],
  ["녹사평대로", "Noksapyeong-daero"],
  ["보문로", "Bomun-ro"],
  ["고려대로", "Goryeodae-ro"],
  ["종암로", "Jongam-ro"],
  ["월곡로", "Wolgok-ro"],
  ["신내로", "Sinnae-ro"],
  ["망우로", "Mangu-ro"],
  ["면목로", "Myeonmok-ro"],
  ["사가정로", "Sagajeong-ro"],
  ["용마산로", "Yongmasan-ro"],
  ["학동로", "Hakdong-ro"],
  ["사당로", "Sadang-ro"],
  ["상도로", "Sangdo-ro"],
  ["신풍로", "Sinpung-ro"],
  ["송파대로", "Songpa-daero"],
  ["강동대로", "Gangdong-daero"],
  ["백제고분로", "Baekjegobun-ro"],
  ["산성대로", "Sanseong-daero"],
  ["오리로", "Ori-ro"],
  ["벚꽃로", "Beotkkot-ro"],
  ["위례성대로", "Wiryeseong-daero"],
  ["동남로", "Dongnam-ro"],
  ["마천로57길", "Macheon-ro 57-gil"],
  ["행궁로", "Haenggung-ro"],
  ["수원천로", "Suwoncheon-ro"],
  ["수정로", "Sujeong-ro"],
  ["철산로", "Cheolsan-ro"],
  ["삼송로", "Samsong-ro"],
  ["장자호수길", "Jangja Hosu-gil"],
  ["산마루로", "Sanmaru-ro"],
  ["예울마루로", "Yeulmaru-ro"],
  ["오동도로", "Odongdo-ro"],
  ["포석로", "Poseok-ro"],
  ["전동성당길", "Jeondong Cathedral-gil"],
  ["기린대로", "Girin-daero"],
  ["명사십리길", "Myeongsasimni-gil"],
  ["인구중앙길", "Ingujungang-gil"],
  ["동해대로", "Donghae-daero"],
  ["중앙시장1길", "Jungang Market 1-gil"],
  ["새터길", "Saeteo-gil"],
  ["덕양구", "Deogyang-gu"],
  ["수원시", "Suwon-si"],
  ["성남시", "Seongnam-si"],
  ["광명시", "Gwangmyeong-si"],
  ["고양시", "Goyang-si"],
  ["구리시", "Guri-si"],
  ["여수시", "Yeosu-si"],
  ["이순신 광장", "Yi Sun-sin Square"],
  ["전주시", "Jeonju-si"],
  ["양양군", "Yangyang-gun"],
  ["통영시", "Tongyeong-si"],
  ["완도군", "Wando-gun"],
  ["완산구", "Wansan-gu"],
  ["팔달구", "Paldal-gu"],
  ["수정구", "Sujeong-gu"],
  ["신지면", "Sinji-myeon"],
  ["현남면", "Hyeonnam-myeon"],
  ["강현면", "Ganghyeon-myeon"],
  ["성산동", "Seongsan-dong"],
  ["태평동", "Taepyeong-dong"],
  ["중앙동", "Jungang-dong"],
  ["서호동", "Seoho-dong"],
  ["장자호수공원", "Jangja Lake Park"],
  ["갈매중앙공원", "Galmae Central Park"],
  ["보관함", "Locker"],
  ["산성", "Sanseong"],
  ["남한산성입구", "Namhansanseong"],
  ["신흥", "Sinheung"],
  ["수진", "Sujin"],
  ["모란", "Moran"],
  ["철산", "Cheolsan"],
  ["광명사거리", "Gwangmyeongsageori"],
  ["지축", "Jichuk"],
  ["낙산 문화관광해설사의 집", "Naksan Tourist Guide Center"],
  ["죽도해변", "Jukdo Beach"],
  ["고기사랑건너편", "Across from Gogisarang"],
  ["공중화장실앞", "In front of the public restroom"],
  ["농협 길건너 삼각지", "Triangle lot across from NH"],
  ["새주소 없음.", "No road address available."]
];

const japaneseTextReplacements = [
  ["서울특별시", "ソウル特別市"],
  ["경상남도", "慶尚南道"],
  ["경상북도", "慶尚北道"],
  ["전라남도", "全羅南道"],
  ["전북특별자치도", "全北特別自治道"],
  ["강원특별자치도", "江原特別自治道"],
  ["경기도", "京畿道"],
  ["인천국제공항", "仁川国際空港"],
  ["제주국제공항", "済州国際空港"],
  ["홍대입구역", "弘大入口駅"],
  ["명동역", "明洞駅"],
  ["동대문디자인플라자", "東大門デザインプラザ"],
  ["서울대입구", "ソウル大入口"],
  ["성신여대입구", "誠信女大入口"],
  ["한성대입구", "漢城大入口"],
  ["동대입구", "東国大入口"],
  ["구로디지털단지", "九老デジタル団地"],
  ["구로디지탈단지", "九老デジタル団地"],
  ["영등포구청", "永登浦区庁"],
  ["양천구청", "陽川区庁"],
  ["마포구청", "麻浦区庁"],
  ["강남구청", "江南区庁"],
  ["강동구청", "江東区庁"],
  ["잠실나루", "蚕室ナル"],
  ["잠실새내", "蚕室セネ"],
  ["신정네거리", "新亭ネゴリ"],
  ["고속터미널", "高速ターミナル"],
  ["남부터미널", "南部ターミナル"],
  ["가락시장", "可楽市場"],
  ["경찰병원", "警察病院"],
  ["총신대입구", "総神大入口"],
  ["종합운동장", "総合運動場"],
  ["서울식물원", "ソウル植物園"],
  ["서울역버스환승센터", "ソウル駅 バス乗換センター"],
  ["동대구역 환승센터", "東大邱駅 乗換センター"],
  ["환승센터", "乗換センター"],
  ["환승통로", "乗換通路"],
  ["관광안내센터", "観光案内センター"],
  ["관광안내 구역", "観光案内エリア"],
  ["해수욕장", "海水浴場"],
  ["지하", "地下"],
  ["기본요금", "基本料金"],
  ["추가요금", "追加料金"],
  ["소형", "小型"],
  ["중형", "中型"],
  ["대형", "大型"],
  ["보관함", "ロッカー"],
  ["사물함", "ロッカー"],
  ["물품보관함", "ロッカー"],
  ["공영", "公共"],
  ["여행자", "旅行者"],
  ["관광", "観光"],
  ["간편", "かんたん"],
  ["짐보관소", "荷物預かり所"],
  ["도착층", "到着階"],
  ["광장", "広場"],
  ["입구", "入口"],
  ["인근 정류장", "周辺の停留所"],
  ["제1터미널", "第1ターミナル"],
  ["온수", "温水"],
  ["서울역", "ソウル駅"],
  ["인천공항", "仁川空港"],
  ["부산역", "釜山駅"],
  ["제주공항", "済州空港"],
  ["동대구역", "東大邱駅"],
  ["강릉역", "江陵駅"],
  ["광화문", "光化門"],
  ["명동", "明洞"],
  ["홍대", "弘大"],
  ["동대문", "東大門"],
  ["해운대", "海雲台"],
  ["황리단길", "皇理団通り"],
  ["강릉", "江陵"],
  ["경주", "慶州"],
  ["서울", "ソウル"],
  ["인천", "仁川"],
  ["부산", "釜山"],
  ["대구", "大邱"],
  ["제주", "済州"],
  ["종로구", "鍾路区"],
  ["중구", "中区"],
  ["용산구", "龍山区"],
  ["마포구", "麻浦区"],
  ["동구", "東区"],
  ["해운대구", "海雲台区"],
  ["제주시", "済州市"],
  ["경주시", "慶州市"],
  ["강릉시", "江陵市"],
  ["강동구", "江東区"],
  ["완산구", "完山区"],
  ["현남면", "県南面"],
  ["강현면", "降峴面"],
  ["성산동", "城山洞"],
  ["태평동", "太平洞"],
  ["중앙동", "中央洞"],
  ["서호동", "西湖洞"],
  ["종로", "鍾路"],
  ["을지로", "乙支路"],
  ["세종대로", "世宗大路"],
  ["한강대로", "漢江大路"],
  ["왕산로", "往十里路"],
  ["돈화문로", "敦化門路"],
  ["율곡로", "栗谷路"],
  ["지봉로", "芝峰路"],
  ["화랑로", "花郎路"],
  ["압구정로", "狎鴎亭路"],
  ["도산대로", "島山大路"],
  ["양재대로", "良才大路"],
  ["증산로", "曽山路"],
  ["이태원로", "梨泰院路"],
  ["전동성당길", "殿洞聖堂ギル"],
  ["기린대로", "麒麟大路"],
  ["마천로57길", "馬川路57ギル"],
  ["마곡동로", "麻谷洞路"],
  ["중앙로", "中央路"],
  ["서소문로", "西小門路"],
  ["경인로3길", "京仁路3ギル"],
  ["경인로67길", "京仁路67ギル"],
  ["경인로114가길", "京仁路114ギル"],
  ["창경궁로", "昌慶宮路"],
  ["장충단로", "奨忠壇路"],
  ["마른내로", "乾川路"],
  ["퇴계로", "退渓路"],
  ["다산로", "茶山路"],
  ["왕십리로", "往十里路"],
  ["아차산로", "峨嵯山路"],
  ["용답길", "龍踏ギル"],
  ["천호대로", "千戸大路"],
  ["능동로", "陵洞路"],
  ["강변역로", "江辺駅路"],
  ["오금로", "梧琴路"],
  ["올림픽로", "オリンピック路"],
  ["테헤란로", "テヘラン路"],
  ["강남대로", "江南大路"],
  ["서초대로", "瑞草大路"],
  ["방배로", "方背路"],
  ["남부순환로", "南部循環路"],
  ["동작대로", "銅雀大路"],
  ["대림로", "大林路"],
  ["도림천로", "道林川路"],
  ["도림로", "道林路"],
  ["목동로3길", "木洞路3ギル"],
  ["새말로", "セマル路"],
  ["당산로", "堂山路"],
  ["양산로", "楊山路"],
  ["양화로", "楊花路"],
  ["신촌로", "新村路"],
  ["진관2로", "津寛2路"],
  ["통일로", "統一路"],
  ["사직로", "社稷路"],
  ["동호로", "東湖路"],
  ["잠원로4길", "蚕院路4ギル"],
  ["신반포로", "新盤浦路"],
  ["서초중앙로", "瑞草中央路"],
  ["일원로", "逸院路"],
  ["광평로", "広平路"],
  ["송파대로", "松坡大路"],
  ["중대로", "中大路"],
  ["상계로", "上渓路"],
  ["동일로", "東一路"],
  ["마들로11길", "マドル路11ギル"],
  ["도봉로", "道峰路"],
  ["동소문로", "東小門路"],
  ["삼선교로", "三仙橋路"],
  ["대학로", "大学路"],
  ["서빙고로", "西氷庫路"],
  ["현충로", "顕忠路"],
  ["과천대로", "果川大路"],
  ["금낭화로", "クムナンファ路"],
  ["양천로", "陽川路"],
  ["하늘길", "ハヌルギル"],
  ["공항대로", "空港大路"],
  ["강서로", "江西路"],
  ["화곡로", "禾谷路"],
  ["오목로", "梧木路"],
  ["여의나루로", "汝矣ナル路"],
  ["여의동로", "汝矣洞路"],
  ["마포대로", "麻浦大路"],
  ["청구로", "青丘路"],
  ["금호로", "金湖路"],
  ["행당로", "杏堂路"],
  ["마장로", "馬場路"],
  ["고덕로", "高徳路"],
  ["서오릉로", "西五陵路"],
  ["불광로", "仏光路"],
  ["연서로", "延曙路"],
  ["수색로", "水色路"],
  ["월드컵로", "ワールドカップ路"],
  ["독막로", "トンマクロ"],
  ["대흥로", "大興路"],
  ["백범로", "白凡路"],
  ["녹사평대로", "緑莎坪大路"],
  ["보문로", "普門路"],
  ["고려대로", "高麗大路"],
  ["종암로", "鍾岩路"],
  ["월곡로", "月谷路"],
  ["신내로", "新内路"],
  ["망우로", "忘憂路"],
  ["면목로", "面牧路"],
  ["사가정로", "四佳亭路"],
  ["용마산로", "龍馬山路"],
  ["학동로", "鶴洞路"],
  ["사당로", "舎堂路"],
  ["상도로", "上道路"],
  ["신풍로", "新豊路"],
  ["백제고분로", "百済古墳路"],
  ["위례성대로", "慰礼城大路"],
  ["동남로", "東南路"],
  ["벚꽃로", "桜花路"],
  ["행궁로", "行宮路"],
  ["수원천로", "水原川路"],
  ["수정로", "寿井路"],
  ["산성대로", "山城大路"],
  ["철산로", "鉄山路"],
  ["오리로", "梧里路"],
  ["삼송로", "三松路"],
  ["장자호수길", "長者湖水ギル"],
  ["산마루로", "サンマル路"],
  ["예울마루로", "イェウルマル路"],
  ["오동도로", "梧桐島路"],
  ["포석로", "鮑石路"],
  ["명사십리길", "明沙十里ギル"],
  ["인구중앙길", "人口中央ギル"],
  ["동해대로", "東海大路"],
  ["중앙시장1길", "中央市場1ギル"],
  ["새터길", "セトギル"],
  ["청량리", "清凉里"],
  ["제기동", "祭基洞"],
  ["신설동", "新設洞"],
  ["동묘앞", "東廟前"],
  ["동대문역사문화공원", "東大門歴史文化公園"],
  ["종로5가", "鍾路5街"],
  ["종로3가", "鍾路3街"],
  ["을지로4가", "乙支路4街"],
  ["신당", "新堂"],
  ["상왕십리", "上往十里"],
  ["왕십리", "往十里"],
  ["한양대", "漢陽大"],
  ["뚝섬", "トゥクソム"],
  ["용답", "龍踏"],
  ["신답", "新踏"],
  ["용두", "龍頭"],
  ["성수", "聖水"],
  ["건대입구", "建大入口"],
  ["구의", "九宜"],
  ["합정", "合井"],
  ["삼성", "三成"],
  ["선릉", "宣陵"],
  ["잠실", "蚕室"],
  ["강변", "江辺"],
  ["잠실나루", "蚕室ナル"],
  ["잠실새내", "蚕室セネ"],
  ["역삼", "駅三"],
  ["교대", "教大"],
  ["서초", "瑞草"],
  ["방배", "方背"],
  ["사당", "舎堂"],
  ["낙성대", "落星垈"],
  ["서울대입구", "ソウル大入口"],
  ["봉천", "奉天"],
  ["신림", "新林"],
  ["신대방", "新大方"],
  ["구로디지탈단지", "九老デジタル団地"],
  ["대림", "大林"],
  ["도림천", "道林川"],
  ["양천구청", "陽川区庁"],
  ["신정네거리", "新亭ネゴリ"],
  ["신도림", "新道林"],
  ["문래", "文来"],
  ["당산", "堂山"],
  ["신촌", "新村"],
  ["이대", "梨大"],
  ["아현", "阿峴"],
  ["충정로", "忠正路"],
  ["구파발", "旧把撥"],
  ["연신내", "延新川"],
  ["불광", "仏光"],
  ["녹번", "緑樊"],
  ["홍제", "弘済"],
  ["무악재", "毋岳峠"],
  ["독립문", "独立門"],
  ["경복궁", "景福宮"],
  ["동대입구", "東国大入口"],
  ["약수", "薬水"],
  ["금호", "金湖"],
  ["옥수", "玉水"],
  ["압구정", "狎鴎亭"],
  ["신사", "新沙"],
  ["잠원", "蚕院"],
  ["남부터미널", "南部ターミナル"],
  ["양재", "良才"],
  ["매봉", "梅峰"],
  ["도곡", "道谷"],
  ["대치", "大峙"],
  ["학여울", "鶴灘"],
  ["대청", "大清"],
  ["일원", "逸院"],
  ["수서", "水西"],
  ["가락시장", "可楽市場"],
  ["경찰병원", "警察病院"],
  ["오금", "梧琴"],
  ["불암산", "仏岩山"],
  ["상계", "上渓"],
  ["노원", "蘆原"],
  ["창동", "倉洞"],
  ["쌍문", "双門"],
  ["수유", "水踰"],
  ["미아", "弥阿"],
  ["미아사거리", "弥阿サゴリ"],
  ["길음", "吉音"],
  ["성신여대입구", "誠信女大入口"],
  ["한성대입구", "漢城大入口"],
  ["혜화", "恵化"],
  ["충무로", "忠武路"],
  ["회현", "会賢"],
  ["숙대입구", "淑大入口"],
  ["삼각지", "三角地"],
  ["신용산", "新龍山"],
  ["이촌", "二村"],
  ["동작", "銅雀"],
  ["총신대입구", "総神大入口"],
  ["남태령", "南泰嶺"],
  ["방화", "傍花"],
  ["개화산", "開花山"],
  ["김포공항", "金浦空港"],
  ["송정", "松亭"],
  ["마곡", "麻谷"],
  ["발산", "鉢山"],
  ["우장산", "牛蔵山"],
  ["화곡", "禾谷"],
  ["까치산", "カチ山"],
  ["신정", "新亭"],
  ["목동", "木洞"],
  ["오목교", "梧木橋"],
  ["양평", "楊平"],
  ["영등포시장", "永登浦市場"],
  ["신길", "新吉"],
  ["여의도", "汝矣島"],
  ["여의나루", "汝矣ナル"],
  ["마포", "麻浦"],
  ["애오개", "アエオゲ"],
  ["서대문", "西大門"],
  ["청구", "青丘"],
  ["신금호", "新金湖"],
  ["행당", "杏堂"],
  ["마장", "馬場"],
  ["답십리", "踏十里"],
  ["장한평", "長漢坪"],
  ["군자", "君子"],
  ["아차산", "峨嵯山"],
  ["광나루", "広ナル"],
  ["천호", "千戸"],
  ["강동", "江東"],
  ["길동", "吉洞"],
  ["올림픽공원", "オリンピック公園"],
  ["명일", "明逸"],
  ["고덕", "高徳"],
  ["상일동", "上一洞"],
  ["응암", "鷹岩"],
  ["역촌", "駅村"],
  ["독바위", "独岩"],
  ["구산", "亀山"],
  ["새절", "セジョル"],
  ["증산", "曽山"],
  ["디지털미디어시티", "デジタルメディアシティ"],
  ["월드컵경기장", "ワールドカップ競技場"],
  ["마포구청", "麻浦区庁"],
  ["망원", "望遠"],
  ["상수", "上水"],
  ["광흥창", "広興倉"],
  ["대흥", "大興"],
  ["공덕", "孔徳"],
  ["효창공원앞", "孝昌公園前"],
  ["녹사평", "緑莎坪"],
  ["이태원", "梨泰院"],
  ["버티고개", "ボティゴゲ"],
  ["창신", "昌信"],
  ["보문", "普門"],
  ["안암", "安岩"],
  ["고려대", "高麗大"],
  ["월곡", "月谷"],
  ["상월곡", "上月谷"],
  ["돌곶이", "トルゴジ"],
  ["화랑대", "花郎台"],
  ["봉화산", "烽火山"],
  ["도봉산", "道峰山"],
  ["수락산", "水落山"],
  ["마들", "マドゥル"],
  ["중계", "中渓"],
  ["하계", "下渓"],
  ["공릉", "孔陵"],
  ["태릉입구", "泰陵入口"],
  ["먹골", "モッコル"],
  ["중화", "中和"],
  ["상봉", "上鳳"],
  ["면목", "面牧"],
  ["사가정", "四佳亭"],
  ["용마산", "龍馬山"],
  ["중곡", "中谷"],
  ["어린이대공원", "オリニ大公園"],
  ["자양", "紫陽"],
  ["청담", "清潭"],
  ["강남구청", "江南区庁"],
  ["학동", "鶴洞"],
  ["논현", "論峴"],
  ["반포", "盤浦"],
  ["내방", "内方"],
  ["이수", "二水"],
  ["남성", "南城"],
  ["숭실대입구", "崇実大入口"],
  ["상도", "上道"],
  ["장승배기", "ジャンスンベギ"],
  ["신대방삼거리", "新大方三叉路"],
  ["보라매", "ポラメ"],
  ["신풍", "新豊"],
  ["남구로", "南九老"],
  ["천왕", "天旺"],
  ["문정", "文井"],
  ["장지", "長旨"],
  ["복정", "福井"],
  ["삼전", "三田"],
  ["석촌고분", "石村古墳"],
  ["송파나루", "松坡ナル"],
  ["한성백제", "漢城百済"],
  ["둔촌오륜", "遁村五輪"],
  ["중앙보훈병원", "中央報勲病院"],
  ["가산디지털", "加山デジタル団地"],
  ["둔촌동", "遁村洞"],
  ["굽은다리", "クブンダリ"],
  ["방이", "芳荑"],
  ["개롱", "開籠"],
  ["거여", "巨余"],
  ["마천", "馬川"],
  ["모란", "牡丹"],
  ["단대오거리", "丹垈オゴリ"],
  ["남한산성입구", "南漢山城入口"],
  ["산성", "山城"],
  ["수진", "寿進"],
  ["신흥", "新興"],
  ["철산", "鉄山"],
  ["광명사거리", "光明サゴリ"],
  ["지축", "紙杻"],
  ["장자호수공원", "長者湖水公園"],
  ["갈매중앙공원", "葛梅中央公園"],
  ["행궁사랑채", "行宮サランチェ"],
  ["화홍사랑채", "華虹サランチェ"],
  ["이순신 광장", "李舜臣広場"],
  ["강남구", "江南区"],
  ["강서구", "江西区"],
  ["광진구", "広津区"],
  ["서초구", "瑞草区"],
  ["동작구", "銅雀区"],
  ["노원구", "蘆原区"],
  ["구로구", "九老区"],
  ["은평구", "恩平区"],
  ["중랑구", "中浪区"],
  ["양천구", "陽川区"],
  ["관악구", "冠岳区"],
  ["강북구", "江北区"],
  ["영등포구", "永登浦区"],
  ["성동구", "城東区"],
  ["동대문구", "東大門区"],
  ["송파구", "松坡区"],
  ["서대문구", "西大門区"],
  ["성북구", "城北区"],
  ["도봉구", "道峰区"],
  ["금천구", "衿川区"],
  ["수원시", "水原市"],
  ["광명시", "光明市"],
  ["성남시", "城南市"],
  ["고양시", "高陽市"],
  ["구리시", "九里市"],
  ["통영시", "統営市"],
  ["완도군", "莞島郡"],
  ["완산구", "完山区"],
  ["팔달구", "八達区"],
  ["수정구", "寿井区"],
  ["덕양구", "徳陽区"],
  ["여수시", "麗水市"],
  ["전주시", "全州市"],
  ["양양군", "襄陽郡"],
  ["신지면", "薪智面"],
  ["웅천친수공원", "熊川親水公園"],
  ["오동도 주차장", "梧桐島駐車場"],
  ["명사십리해수욕장", "明沙十里海水浴場"],
  ["황리단길 생활문화센터", "皇理団通り生活文化センター"],
  ["생활문화센터", "生活文化センター"],
  ["중앙시장", "中央市場"],
  ["서호시장", "西湖市場"],
  ["고객지원센터", "顧客支援センター"],
  ["고기사랑건너편", "焼肉店向かい"],
  ["공중화장실앞", "公衆トイレ前"],
  ["농협 길건너 삼각지", "農協向かいの三角地"],
  ["죽도해변", "竹島海辺"],
  ["낙산 문화관광해설사의 집", "洛山文化観光解説の家"],
  ["경기전 여행자 라운지", "慶基殿 旅行者ラウンジ"],
  ["전주종합관광안내소", "全州総合観光案内所"],
  ["새주소 없음.", "新住所なし。"],
  ["기본요금 부과 이후", "基本料金適用後は"],
  ["1시간당", "1時間ごとに"],
  ["추가요금발생", "追加料金が発生します"],
  ["최대5시간", "最長5時間"],
  ["무료", "無料"],
  ["원", "ウォン"],
  ["대로", "大路"],
  ["로", "路"],
  ["길", "ギル"],
  ["구", "区"],
  ["군", "郡"]
];

const chineseTextReplacements = [
  ["서울특별시", "首尔特别市"],
  ["경상남도", "庆尚南道"],
  ["경상북도", "庆尚北道"],
  ["전라남도", "全罗南道"],
  ["전북특별자치도", "全北特别自治道"],
  ["강원특별자치도", "江原特别自治道"],
  ["경기도", "京畿道"],
  ["인천국제공항", "仁川国际机场"],
  ["제주국제공항", "济州国际机场"],
  ["홍대입구역", "弘大入口站"],
  ["명동역", "明洞站"],
  ["동대문디자인플라자", "东大门设计广场"],
  ["서울대입구", "首尔大学入口"],
  ["성신여대입구", "诚信女大入口"],
  ["한성대입구", "汉城大入口"],
  ["동대입구", "东大入口"],
  ["구로디지털단지", "九老数码园区"],
  ["구로디지탈단지", "九老数码园区"],
  ["영등포구청", "永登浦区厅"],
  ["양천구청", "阳川区厅"],
  ["잠실나루", "蚕室渡口"],
  ["잠실새내", "蚕室新川"],
  ["신정네거리", "新亭十字路口"],
  ["고속터미널", "高速客运站"],
  ["남부터미널", "南部客运站"],
  ["가락시장", "可乐市场"],
  ["경찰병원", "警察医院"],
  ["총신대입구", "总神大入口"],
  ["동대문역사문화공원", "东大门历史文化公园"],
  ["종합운동장", "综合运动场"],
  ["서울식물원", "首尔植物园"],
  ["서울역버스환승센터", "首尔站公共交通换乘中心"],
  ["동대구역 환승센터", "东大邱站换乘中心"],
  ["환승센터", "换乘中心"],
  ["환승통로", "换乘通道"],
  ["관광안내센터", "旅游咨询中心"],
  ["관광안내 구역", "旅游咨询区"],
  ["해수욕장", "海水浴场"],
  ["지하", "地下"],
  ["기본요금", "基本费用"],
  ["추가요금", "附加费用"],
  ["소형", "小型"],
  ["중형", "中型"],
  ["대형", "大型"],
  ["물품보관함", "储物柜"],
  ["공영", "公共"],
  ["여행자", "旅行者"],
  ["관광", "旅游"],
  ["간편", "便捷"],
  ["짐보관소", "行李寄存处"],
  ["도착층", "到达层"],
  ["광장", "广场"],
  ["입구", "入口"],
  ["인근 정류장", "附近站点"],
  ["제1터미널", "第1航站楼"],
  ["온수", "温水"],
  ["석계", "石溪"],
  ["종각", "钟阁"],
  ["시청", "市厅"],
  ["을지로3가", "乙支路3街"],
  ["을지로4가", "乙支路4街"],
  ["건대입구", "建大入口"],
  ["강변", "江边"],
  ["역삼", "驿三"],
  ["강남", "江南"],
  ["교대", "教大"],
  ["서초", "瑞草"],
  ["방배", "方背"],
  ["사당", "舍堂"],
  ["낙성대", "落星垈"],
  ["봉천", "奉天"],
  ["신림", "新林"],
  ["신대방", "新大方"],
  ["대림", "大林"],
  ["도림천", "道林川"],
  ["신도림", "新道林"],
  ["문래", "文来"],
  ["독립문", "独立门"],
  ["잠원", "蚕院"],
  ["당산", "堂山"],
  ["신촌", "新村"],
  ["이대", "梨大"],
  ["아현", "阿岘"],
  ["충정로", "忠正路"],
  ["구파발", "旧把拨"],
  ["연신내", "延新川"],
  ["불광", "佛光"],
  ["녹번", "绿樊"],
  ["홍제", "弘济"],
  ["무악재", "毋岳岭"],
  ["경복궁", "景福宫"],
  ["약수", "药水"],
  ["금호", "金湖"],
  ["옥수", "玉水"],
  ["압구정", "狎鸥亭"],
  ["신사", "新沙"],
  ["양재", "良才"],
  ["매봉", "梅峰"],
  ["도곡", "道谷"],
  ["대치", "大峙"],
  ["학여울", "鹤滩"],
  ["대청", "大清"],
  ["일원", "逸院"],
  ["수서", "水西"],
  ["오금", "梧琴"],
  ["불암산", "佛岩山"],
  ["상계", "上溪"],
  ["노원", "芦原"],
  ["창동", "仓洞"],
  ["쌍문", "双门"],
  ["수유", "水逾"],
  ["미아사거리", "弥阿十字路口"],
  ["미아", "弥阿"],
  ["길음", "吉音"],
  ["혜화", "惠化"],
  ["충무로", "忠武路"],
  ["회현", "会贤"],
  ["숙대입구", "淑大入口"],
  ["삼각지", "三角地"],
  ["신용산", "新龙山"],
  ["이촌", "二村"],
  ["동작", "铜雀"],
  ["남태령", "南泰岭"],
  ["방화", "傍花"],
  ["개화산", "开花山"],
  ["김포공항", "金浦机场"],
  ["송정", "松亭"],
  ["마곡", "麻谷"],
  ["발산", "发山"],
  ["우장산", "牛藏山"],
  ["화곡", "禾谷"],
  ["까치산", "喜鹊山"],
  ["신정", "新亭"],
  ["목동", "木洞"],
  ["오목교", "梧木桥"],
  ["양평", "杨平"],
  ["영등포시장", "永登浦市场"],
  ["신길", "新吉"],
  ["여의도", "汝矣岛"],
  ["여의나루", "汝矣渡口"],
  ["마포", "麻浦"],
  ["애오개", "阿岘岭"],
  ["서대문", "西大门"],
  ["청구", "青丘"],
  ["신금호", "新金湖"],
  ["행당", "杏堂"],
  ["마장", "马场"],
  ["답십리", "踏十里"],
  ["장한평", "长汉坪"],
  ["군자", "君子"],
  ["아차산", "峨嵯山"],
  ["광나루", "广渡口"],
  ["천호", "千户"],
  ["강동", "江东"],
  ["길동", "吉洞"],
  ["올림픽공원", "奥林匹克公园"],
  ["명일", "明逸"],
  ["고덕", "高德"],
  ["상일동", "上一洞"],
  ["문정", "文井"],
  ["장지", "长旨"],
  ["복정", "福井"],
  ["삼전", "三田"],
  ["석촌고분", "石村古坟"],
  ["송파나루", "松坡渡口"],
  ["한성백제", "汉城百济"],
  ["둔촌오륜", "遁村五轮"],
  ["중앙보훈병원", "中央报勋医院"],
  ["가산디지털", "加山数码园区"],
  ["둔촌동", "遁村洞"],
  ["굽은다리", "曲桥"],
  ["방이", "芳荑"],
  ["개롱", "开笼"],
  ["거여", "巨余"],
  ["마천", "马川"],
  ["응암", "鹰岩"],
  ["역촌", "驿村"],
  ["독바위", "独岩"],
  ["구산", "龟山"],
  ["새절", "新切"],
  ["증산", "曾山"],
  ["디지털미디어시티", "数字媒体城"],
  ["월드컵경기장", "世界杯竞技场"],
  ["망원", "望远"],
  ["상수", "上水"],
  ["광흥창", "广兴仓"],
  ["대흥", "大兴"],
  ["효창공원앞", "孝昌公园前"],
  ["녹사평", "绿莎坪"],
  ["이태원", "梨泰院"],
  ["버티고개", "獐岘"],
  ["창신", "昌信"],
  ["보문", "普门"],
  ["안암", "安岩"],
  ["고려대", "高丽大"],
  ["월곡", "月谷"],
  ["상월곡", "上月谷"],
  ["돌곶이", "石串"],
  ["화랑대", "花郎台"],
  ["봉화산", "烽火山"],
  ["도봉산", "道峰山"],
  ["수락산", "水落山"],
  ["마들", "马得"],
  ["중계", "中溪"],
  ["하계", "下溪"],
  ["공릉", "孔陵"],
  ["먹골", "墨谷"],
  ["중화", "中和"],
  ["상봉", "上凤"],
  ["면목", "面牧"],
  ["사가정", "四佳亭"],
  ["용마산", "龙马山"],
  ["중곡", "中谷"],
  ["어린이대공원", "儿童大公园"],
  ["자양", "紫阳"],
  ["청담", "清潭"],
  ["강남구청", "江南区厅"],
  ["마포구청", "麻浦区厅"],
  ["학동", "鹤洞"],
  ["논현", "论岘"],
  ["반포", "盘浦"],
  ["내방", "内方"],
  ["이수", "二水"],
  ["남성", "南城"],
  ["숭실대입구", "崇实大入口"],
  ["상도", "上道"],
  ["장승배기", "将丞里"],
  ["신대방삼거리", "新大方三岔路口"],
  ["태릉입구", "泰陵入口"],
  ["단대오거리", "丹垈五岔路口"],
  ["공덕", "孔德"],
  ["보라매", "甫罗鹰"],
  ["신풍", "新丰"],
  ["남구로", "南九老"],
  ["천왕", "天旺"],
  ["암사", "岩寺"],
  ["강동구청", "江东区厅"],
  ["몽촌토성", "梦村土城"],
  ["석촌", "石村"],
  ["송파", "松坡"],
  ["서울역", "首尔站"],
  ["인천공항", "仁川机场"],
  ["부산역", "釜山站"],
  ["제주공항", "济州机场"],
  ["동대구역", "东大邱站"],
  ["강릉역", "江陵站"],
  ["광화문", "光化门"],
  ["명동", "明洞"],
  ["홍대", "弘大"],
  ["동대문", "东大门"],
  ["해운대", "海云台"],
  ["황리단길", "皇理团路"],
  ["강릉", "江陵"],
  ["경주", "庆州"],
  ["서울", "首尔"],
  ["인천", "仁川"],
  ["부산", "釜山"],
  ["대구", "大邱"],
  ["제주", "济州"],
  ["종로구", "钟路区"],
  ["중구", "中区"],
  ["용산구", "龙山区"],
  ["마포구", "麻浦区"],
  ["동구", "东区"],
  ["해운대구", "海云台区"],
  ["제주시", "济州市"],
  ["경주시", "庆州市"],
  ["강릉시", "江陵市"],
  ["종로", "钟路"],
  ["을지로", "乙支路"],
  ["세종대로", "世宗大路"],
  ["한강대로", "汉江大路"],
  ["왕산로", "往十里路"],
  ["돈화문로", "敦化门路"],
  ["율곡로", "栗谷路"],
  ["지봉로", "地峰路"],
  ["화랑로", "花郎路"],
  ["마곡동로", "麻谷洞路"],
  ["중앙로", "中央路"],
  ["청량리", "清凉里"],
  ["제기동", "祭基洞"],
  ["신설동", "新设洞"],
  ["동묘앞", "东庙前"],
  ["동대문역사문화공원", "东大门历史文化公园"],
  ["종로5가", "钟路5街"],
  ["종로3가", "钟路3街"],
  ["을지로4가", "乙支路4街"],
  ["신당", "新堂"],
  ["상왕십리", "上往十里"],
  ["왕십리", "往十里"],
  ["한양대", "汉阳大"],
  ["뚝섬", "纛岛"],
  ["용답", "龙踏"],
  ["신답", "新踏"],
  ["용두", "龙头"],
  ["성수", "圣水"],
  ["건대입구", "建大入口"],
  ["구의", "九宜"],
  ["합정", "合井"],
  ["삼성", "三成"],
  ["선릉", "宣陵"],
  ["잠실", "蚕室"],
  ["모란", "牡丹"],
  ["단대오거리", "丹垈五거리"],
  ["남한산성입구", "南汉山城入口"],
  ["산성", "山城"],
  ["수진", "寿进"],
  ["신흥", "新兴"],
  ["철산", "铁山"],
  ["광명사거리", "光明十字路口"],
  ["지축", "纸杻"],
  ["장자호수공원", "长者湖水公园"],
  ["갈매중앙공원", "葛梅中央公园"],
  ["행궁사랑채", "行宫舍廊房"],
  ["화홍사랑채", "华虹舍廊房"],
  ["이순신 광장", "李舜臣广场"],
  ["고기사랑건너편", "烤肉店对面"],
  ["고객지원센터", "顾客服务中心"],
  ["농협 길건너 삼각지", "农协对面三角地"],
  ["강남구", "江南区"],
  ["강서구", "江西区"],
  ["광진구", "广津区"],
  ["서초구", "瑞草区"],
  ["동작구", "铜雀区"],
  ["노원구", "芦原区"],
  ["구로구", "九老区"],
  ["은평구", "恩平区"],
  ["중랑구", "中浪区"],
  ["양천구", "阳川区"],
  ["관악구", "冠岳区"],
  ["강북구", "江北区"],
  ["강동구", "江东区"],
  ["영등포구", "永登浦区"],
  ["성동구", "城东区"],
  ["동대문구", "东大门区"],
  ["송파구", "松坡区"],
  ["서대문구", "西大门区"],
  ["성북구", "城北区"],
  ["도봉구", "道峰区"],
  ["금천구", "衿川区"],
  ["통영시", "统营市"],
  ["완도군", "莞岛郡"],
  ["완산구", "完山区"],
  ["팔달구", "八达区"],
  ["수정구", "寿井区"],
  ["여수시", "丽水市"],
  ["전주시", "全州市"],
  ["양양군", "襄阳郡"],
  ["수원시", "水原市"],
  ["성남시", "城南市"],
  ["광명시", "光明市"],
  ["고양시", "高阳市"],
  ["구리시", "九里市"],
  ["덕양구", "德阳区"],
  ["웅천친수공원", "雄川亲水公园"],
  ["오동도 주차장", "梧桐岛停车场"],
  ["명사십리해수욕장", "鸣沙十里海水浴场"],
  ["황리단길 생활문화센터", "皇理团路生活文化中心"],
  ["중앙시장", "中央市场"],
  ["공중화장실앞", "公厕前"],
  ["서호시장", "西湖市场"],
  ["죽도해변 사물함", "竹岛海边储物柜"],
  ["낙산 문화관광해설사의 집 사물함", "洛山文化旅游解说员之家储物柜"],
  ["경기전 여행자 라운지", "庆基殿旅行者休息厅"],
  ["전주종합관광안내소", "全州综合旅游咨询中心"],
  ["보관함", "储物柜"],
  ["사물함", "储物柜"],
  ["마곡동로", "麻谷洞路"],
  ["서소문로", "西小门路"],
  ["창경궁로", "昌庆宫路"],
  ["장충단로", "奖忠坛路"],
  ["마른내로", "马场内路"],
  ["퇴계로", "退溪路"],
  ["다산로", "茶山路"],
  ["왕십리로", "往十里路"],
  ["용답길", "龙踏街"],
  ["강변역로", "江边站路"],
  ["오금로", "梧琴路"],
  ["올림픽로", "奥林匹克路"],
  ["테헤란로", "德黑兰路"],
  ["강남대로", "江南大路"],
  ["방배로", "方背路"],
  ["남부순환로", "南部循环路"],
  ["대림로", "大林路"],
  ["도림천로", "道林川路"],
  ["도림로", "道林路"],
  ["목동로3길", "木洞路3街"],
  ["새말로", "新村路"],
  ["당산로", "堂山路"],
  ["양산로", "杨山路"],
  ["양화로", "杨花路"],
  ["신촌로", "新村路"],
  ["진관2로", "津宽2路"],
  ["통일로", "统一路"],
  ["사직로", "社稷路"],
  ["동호로", "东湖路"],
  ["잠원로4길", "蚕院路4街"],
  ["서초중앙로", "瑞草中央路"],
  ["광평로", "广平路"],
  ["중대로", "中大路"],
  ["상계로", "上溪路"],
  ["마들로11길", "马德路11街"],
  ["도봉로", "道峰路"],
  ["동소문로", "东小门路"],
  ["삼선교로", "三仙桥路"],
  ["대학로", "大学路"],
  ["서빙고로", "西冰库路"],
  ["현충로", "显忠路"],
  ["경인로3길", "京仁路3街"],
  ["경인로67길", "京仁路67街"],
  ["경인로114가길", "京仁路114街"],
  ["능동로", "陵洞路"],
  ["서초대로", "瑞草大路"],
  ["동작대로", "铜雀大路"],
  ["신반포로", "新盘浦路"],
  ["과천대로", "果川大路"],
  ["금낭화로", "金囊花路"],
  ["양천로", "阳川路"],
  ["하늘길", "天空路"],
  ["화곡로", "禾谷路"],
  ["오목로", "梧木路"],
  ["여의나루로", "汝矣渡口路"],
  ["청구로", "青丘路"],
  ["금호로", "金湖路"],
  ["행당로", "杏堂路"],
  ["마장로", "马场路"],
  ["고덕로", "高德路"],
  ["서오릉로", "西五陵路"],
  ["불광로", "佛光路"],
  ["연서로", "延曙路"],
  ["수색로", "水色路"],
  ["대흥로", "大兴路"],
  ["백범로", "白凡路"],
  ["녹사평대로", "绿莎坪大路"],
  ["보문로", "普门路"],
  ["고려대로", "高丽大路"],
  ["종암로", "钟岩路"],
  ["월곡로", "月谷路"],
  ["신내로", "新内路"],
  ["망우로", "忘忧路"],
  ["면목로", "面牧路"],
  ["사가정로", "四佳亭路"],
  ["용마산로", "龙马山路"],
  ["학동로", "鹤洞路"],
  ["사당로", "舍堂路"],
  ["상도로", "上道路"],
  ["신풍로", "新丰路"],
  ["송파대로", "松坡大路"],
  ["여의동로", "汝矣东路"],
  ["독막로", "独幕路"],
  ["백제고분로", "百济古坟路"],
  ["위례성대로", "慰礼城大路"],
  ["동남로", "东南路"],
  ["마천로57길", "马川路57街"],
  ["행궁로", "行宫路"],
  ["수원천로", "水原川路"],
  ["수정로", "寿井路"],
  ["철산로", "铁山路"],
  ["벚꽃로", "樱花路"],
  ["삼송로", "三松路"],
  ["장자호수길", "长者湖水街"],
  ["산마루로", "山脊路"],
  ["예울마루로", "艺蔚楼路"],
  ["오동도로", "梧桐岛路"],
  ["백제고분로", "百济古坟路"],
  ["위례성대로", "慰礼城大路"],
  ["동남로", "东南路"],
  ["마천로57길", "马川路57街"],
  ["포석로", "鲍石路"],
  ["여의동로", "汝矣东路"],
  ["행궁로26", "行宫路26"],
  ["신지면", "薪智面"],
  ["현남면", "县南面"],
  ["강현면", "降岘面"],
  ["태평동", "太平洞"],
  ["중앙동", "中央洞"],
  ["서호동", "西湖洞"],
  ["성산동", "城山洞"],
  ["강서로", "江西路"],
  ["증산로", "曾山路"],
  ["공항대로", "机场大路"],
  ["월드컵로", "世界杯路"],
  ["도산대로", "岛山大路"],
  ["압구정로", "狎鸥亭路"],
  ["양재대로", "良才大路"],
  ["천호대로", "千户大路"],
  ["아차산로", "峨嵯山路"],
  ["동일로", "东一路"],
  ["오리로", "梧里路"],
  ["전동성당길", "殿洞圣堂街"],
  ["기린대로", "麒麟大路"],
  ["명사십리길", "鸣沙十里路"],
  ["인구중앙길", "仁丘中央街"],
  ["동해대로", "东海大路"],
  ["중앙시장1길", "中央市场1街"],
  ["새터길", "新基街"],
  ["새주소 없음.", "暂无新地址。"],
  ["대로", "大路"],
  ["로", "路"],
  ["길", "街"],
  ["구", "区"],
  ["시", "市"],
  ["군", "郡"]
];

function localizeMappedValue(value, t, translations) {
  if (!value) return value;
  return translations[t.locale]?.[value] ?? value;
}

function replaceTerms(value, replacements) {
  return [...replacements]
    .sort((a, b) => b[0].length - a[0].length)
    .reduce((text, [source, target]) => text.replaceAll(source, target), value);
}

function localizeDynamicText(value, t) {
  if (!value) return value;

  if (t.locale === "en") {
    return replaceTerms(value, [...Object.entries(localizedDistricts.en), ...englishTextReplacements]).replace(
      /(\d+)호선/g,
      "Line $1"
    );
  }

  if (t.locale === "ja") {
    return replaceTerms(value, japaneseTextReplacements).replace(/(\d+)호선/g, "$1号線");
  }

  if (t.locale === "zh") {
    return replaceTerms(value, chineseTextReplacements).replace(/(\d+)호선/g, "$1号线");
  }

  return value;
}

function stripNumericParentheses(value) {
  return value
    .replace(/\(\s*[\d\s,~\-–—]+\s*\)/g, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function collapseRepeatedTerms(value) {
  const terms = value.split(/\s+/);
  return terms
    .filter((term, index) => term !== terms[index - 1])
    .join(" ");
}

function localizeJapaneseLockerName(value) {
  return japanesePlaceNames
    .reduce((name, [korean, japanese]) => name.replaceAll(korean, japanese), value)
    .replace(/(\d+)호선/g, "$1号線");
}

export function formatLockerName(locker, t) {
  const cleanedName = collapseRepeatedTerms(stripNumericParentheses(locker.name));
  const localizedName = localizeMappedValue(cleanedName, t, localizedLockerNames);

  if (localizedName !== cleanedName || t.locale === "zh" || t.locale === "en") {
    return collapseRepeatedTerms(localizeDynamicText(localizedName, t));
  }

  if (t.locale === "ja") {
    return collapseRepeatedTerms(localizeDynamicText(localizeJapaneseLockerName(cleanedName), t));
  }

  return cleanedName;
}

export function formatDistrict(value, t) {
  return localizeDynamicText(localizeMappedValue(value, t, localizedDistricts), t);
}

export function formatAddress(value, t) {
  return localizeDynamicText(localizeMappedValue(value, t, localizedAddresses), t);
}

export function formatLandmark(value, t) {
  const localizedValue = t.landmarkNames?.[value] ?? localizeMappedValue(value, t, localizedDistricts);
  return localizeDynamicText(localizedValue, t);
}

export function formatBusStop(value, t) {
  const directLocalizedValue = localizeMappedValue(value, t, localizedBusStops);
  if (directLocalizedValue !== value) {
    return localizeDynamicText(directLocalizedValue, t);
  }

  const areaStopMatch = value?.match(/^(.*) area stop$/);
  if (areaStopMatch) {
    const baseName = areaStopMatch[1];
    const localizedBase = formatLandmark(baseName, t);

    if (t.locale === "ko") return `${localizedBase} 인근 정류장`;
    if (t.locale === "zh") return `${localizedBase} 附近站点`;
    if (t.locale === "ja") return `${localizedBase} 周辺の停留所`;
    return `${localizedBase} area stop`;
  }

  return localizeDynamicText(value, t);
}

export function formatPrice(value, t) {
  const localizedValue = localizeDynamicText(localizeMappedValue(value, t, localizedPrices), t);

  if (t.locale === "en") {
    return localizedValue.replace(/(\d[\d,]*)원/g, "$1 KRW");
  }

  if (t.locale === "ja") {
    return localizedValue
      .replace(/(\d[\d,]*)원/g, "$1ウォン")
      .replace(/최대\s*(\d+)시간/g, "最長$1時間")
      .replace(/(\d+)시간/g, "$1時間");
  }

  return localizedValue;
}

export function formatOpenHours(value, t) {
  return localizeDynamicText(localizeMappedValue(value, t, localizedOpenHours), t);
}

export function formatBusRouteLabel(value, t) {
  return localizeDynamicText(localizeMappedValue(value, t, localizedBusRouteLabels), t);
}

export function formatDuration(minutes, t) {
  return `${minutes}${t.minuteSuffix ?? "m"}`;
}

export function formatAvailableUnits(value, total, t) {
  if (t?.locale === "ko") {
    return `${value}칸 남음 · 총 ${total}칸`;
  }

  if (t?.locale === "zh") {
    return `剩余${value}格 · 共${total}格`;
  }

  if (t?.locale === "ja") {
    return `${value}枠空き · 全${total}枠`;
  }

  return `${value} left · ${total} total`;
}

export function formatSupportLabel(supported, t) {
  return supported ? t.supported ?? "Yes" : t.notSupported ?? "No";
}

export function getAvailabilityRatio(locker) {
  return locker.totalUnits === 0 ? 0 : locker.availableUnits / locker.totalUnits;
}

export function getCrowdingScore(locker) {
  return 1 - getAvailabilityRatio(locker);
}

export function haversineDistanceKm(from, to) {
  const toRadians = (value) => (value * Math.PI) / 180;
  const earthRadius = 6371;
  const dLat = toRadians(to.lat - from.lat);
  const dLon = toRadians(to.lon - from.lon);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRadians(from.lat)) *
      Math.cos(toRadians(to.lat)) *
      Math.sin(dLon / 2) ** 2;
  return earthRadius * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

export function matchesSearch(locker, query) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return true;

  const searchAliases = {
    Seoul: ["서울", "ソウル", "首尔"],
    Busan: ["부산", "釜山"],
    Incheon: ["인천", "仁川"],
    Jeju: ["제주", "済州", "济州"],
    Gyeongju: ["경주", "慶州", "庆州"],
    Gangneung: ["강릉", "江陵"],
    Daegu: ["대구", "大邱"],
    Gyeonggi: ["경기", "경기도", "京畿"],
    Gangwon: ["강원", "강원도", "江原"],
    Jeollanamdo: ["전남", "전라남도", "全羅南道", "全罗南道"],
    Jeonbuk: ["전북", "전라북도", "全北", "全羅北道", "全罗北道"],
    Gyeongsangbukdo: ["경북", "경상북도", "慶尚北道", "庆尚北道"],
    Gyeongsangnamdo: ["경남", "경상남도", "慶尚南道", "庆尚南道"],
    "수원시": ["수원", "Suwon", "Suwon-si", "水原", "水原市"],
    Gwanghwamun: ["광화문", "光化門", "光化门"],
    Myeongdong: ["명동", "明洞"],
    "Seoul Station": ["서울역", "ソウル駅", "首尔站"],
    Hongdae: ["홍대", "弘大"],
    Dongdaemun: ["동대문", "東大門", "东大门"],
    "Incheon Airport": ["인천공항", "仁川空港", "仁川机场"],
    "Busan Station": ["부산역", "釜山駅", "釜山站"],
    Haeundae: ["해운대", "海雲台", "海云台"],
    "Jeju Airport": ["제주공항", "済州空港", "济州机场"],
    "Hwangnidan-gil": ["황리단길", "皇理団通り", "皇理团路"],
    "Gangneung Station": ["강릉역", "江陵駅", "江陵站"],
    "Dongdaegu Station": ["동대구역", "대구역", "東大邱駅", "大邱站"]
  };

  const aliases = [
    ...(searchAliases[locker.region] ?? []),
    ...(searchAliases[locker.nearbyLandmark] ?? [])
  ];
  const searchCorpus = [
    locker.name,
    locker.region,
    locker.district,
    locker.address,
    locker.nearbyLandmark,
    locker.nearestBusStop,
    ...aliases
  ]
    .join(" ")
    .toLowerCase();

  if (searchCorpus.includes(normalized)) {
    return true;
  }

  if (aliases.some((alias) => normalized.includes(alias.toLowerCase()))) {
    return true;
  }

  const tokens = normalized
    .split(/[\s,./!?()\-_:;]+/)
    .map((token) => token.trim())
    .filter(Boolean)
    .filter((token) => token.length >= 2);

  return tokens.some((token) => searchCorpus.includes(token));
}

export function sortLockers(lockers, sortMode, currentLocation = null) {
  const sorted = [...lockers];

  if (sortMode === "leastCrowded") {
    return sorted.sort((a, b) => {
      if (statusStyles[a.availabilityStatus].order !== statusStyles[b.availabilityStatus].order) {
        return statusStyles[a.availabilityStatus].order - statusStyles[b.availabilityStatus].order;
      }

      return getCrowdingScore(a) - getCrowdingScore(b);
    });
  }

  if (sortMode === "fastestBus") {
    return sorted.sort((a, b) => a.estimatedBusMinutes - b.estimatedBusMinutes);
  }

  if (currentLocation) {
    return sorted.sort((a, b) => {
      const distanceA =
        a.distanceFromUserKm ??
        haversineDistanceKm(currentLocation, { lat: a.latitude, lon: a.longitude });
      const distanceB =
        b.distanceFromUserKm ??
        haversineDistanceKm(currentLocation, { lat: b.latitude, lon: b.longitude });
      return distanceA - distanceB;
    });
  }

  return sorted.sort((a, b) => a.estimatedWalkMinutes - b.estimatedWalkMinutes);
}

export function summarize(lockers) {
  return lockers.reduce(
    (summary, locker) => {
      summary.total += locker.totalUnits;
      summary.available += locker.availableUnits;
      summary[locker.availabilityStatus] += 1;
      return summary;
    },
    { total: 0, available: 0, Available: 0, "Almost Full": 0, Full: 0 }
  );
}

export function getAlternative(lockers, currentLocker) {
  return lockers
    .filter((locker) => locker.id !== currentLocker.id)
    .filter((locker) => locker.availabilityStatus !== "Full")
    .sort((a, b) => {
      const sameLandmarkA = a.nearbyLandmark === currentLocker.nearbyLandmark ? -1 : 0;
      const sameLandmarkB = b.nearbyLandmark === currentLocker.nearbyLandmark ? -1 : 0;
      if (sameLandmarkA !== sameLandmarkB) return sameLandmarkA - sameLandmarkB;
      return getCrowdingScore(a) - getCrowdingScore(b);
    })[0];
}

export function getLanguageLabel(languageCode, t) {
  return (
    t?.languageLabels?.[languageCode] ??
    {
      ko: "KO",
      en: "EN",
      zh: "中文",
      ja: "日本語"
    }[languageCode]
  );
}
